### PR TITLE
fix: move margins to button in slideshow

### PR DESCRIPTION
**Pull request by andrewreifman**
## What/Why?
In the Slideshow component, if a slide description is removed, there was no spacing between the title and button. Margin classes were changed to ensure the title, description, and button had the proper spacing between them at all times.

## Testing
View the Slideshow component and hide any slide description.

### CODE REVIEW

**Review by jorgemoya — CHANGES_REQUESTED** [review]
`pnpm-lock` shouldn't need to be updated. Component changes look good tho!

**Comment by andrewreifman** [comment]
> `pnpm-lock` shouldn't need to be updated. Component changes look good tho!

@jorgemoya I assume it changed the lock file by me just running `pnpm install`. Do I just need to undo that change in the file and push it back up?

I also was about to ask in Slack what I should do about the lint failures in the build that aren't related to my PR.

**Comment by jorgemoya** [comment]
> > `pnpm-lock` shouldn't need to be updated. Component changes look good tho!
> 
> 
> 
> @jorgemoya I assume it changed the lock file by me just running `pnpm install`. Do I just need to undo that change in the file and push it back up?
> 
> 
> 
> I also was about to ask in Slack what I should do about the lint failures in the build that aren't related to my PR.

I would just undo the file and push it back up. We can then investigate if we need to update the lock file.

**Comment by andrewreifman** [comment]
@jorgemoya This is ready for another review

**Pull request closed without merging**
