### PR TITLE
fix(core): improve redirect behavior after creating new address

### PR DESCRIPTION
**Pull request by bc-yevhenii-buliuk**
## What/Why?
This PR improves redirect behavior after adding a new address, namely, it adds a banner about the successful creation of a new address.

## Testing
locally

**before:**

https://github.com/user-attachments/assets/58b6aff4-c7a2-43af-8455-8e356bdef625

**after:**

https://github.com/user-attachments/assets/69c71315-80fc-43bf-b8c5-4304ab114246

### CODE REVIEW

**Review by bc-alexsaiannyi — APPROVED** [review]
good job 👍

**Review by jorgemoya — APPROVED** [review]

**Review by yurytut1993 — APPROVED** [review]

**Review by bc-azvierieva — CHANGES_REQUESTED** [review]
Comment in Jira ticket is added with details on what should be changed. 
Regarding failing UI tests - it is a general problem, not related to this PR. I am working to fix this, and will push some changes to Address test after fixing general issue.

**Comment by bc-yevhenii-buliuk** [comment]
> Can we rebase and try to get this PR merged?

@jorgemoya for this PR I need to add some small edits after testing. I'll deal with this as soon as possible.

**Review by bc-azvierieva — APPROVED** [review]
Nicely done!

**Pull request merged**
